# -*- coding: utf-8 -*-
"""PROYEK AKHIR DICODING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/meakhelg/proyek-akhir-dicoding.4bb4f642-2139-4b6e-9e17-bc33dc3b14c2.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260206/auto/storage/goog4_request%26X-Goog-Date%3D20260206T112725Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D59219204c9ad731c6f252b6c86c834cf3f8fde895d8fe05b1b9f61933ccf7c9d5013888a9e9c397b239c5f5a4b5fa93205121b40bce5e48bfe5874d62a6aad294ca4e008c55b0693ffa2cd7cd7b9156a9e98ec154b1d89b45e000279ff830f8499c8104e917b42f8ed069c0c3ef9a54f6db0695f153b8934042b5d16c9742ae34a3a725383cfbeff5f198640831276e1915d6611a67034f3d5518a71e8beb10fd2d8407621cdfc990c607e97aac65b0858f09643d2e75129756a0a7e22aa5547a2bcb643ccc2ec619b5d1d74e092fd7df929ac295a1c780d7874554f3fbb8e3e590706b9417dbbda943fe319b81f1ae213d1fde583c63a6c11a1aad597ebf6fe

# **Proyek Klasifikasi Gambar**
## **Data Diri**
- **Nama:** Meakhel Gunawan
- **Email:** meakhel220504@gmail.com
- **ID Dicoding:** meakhelg
- **Dataset:** https://www.kaggle.com/datasets/alessiocorrado99/animals10/data

# <font color='yellow'> **Import Library**</font>
"""

!pip install split-folders

!pip install tensorflowjs

# Library umum
import os, shutil
from PIL import Image
import splitfolders
from pathlib import Path
import numpy as np
import pandas as pd
import seaborn as sns
import splitfolders
from itertools import islice
import importlib.util
from tqdm import tqdm
from glob import glob
import numpy as np
import subprocess
import matplotlib.pyplot as plt
import logging
import time

# Library tensorflow
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, applications, regularizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from tensorflow.keras.preprocessing import image
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.preprocessing import image
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from keras.models import Sequential
import tensorflowjs as tfjs

# Library sklearn
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""# <font color='yellow'> **Data Preparation**</font>"""

def convert_path_to_df(dataset):
    image_dir = Path(dataset)

    # Get filepaths for all supported formats
    extensions = ['*.jpg', '*.JPG', '*.jpeg', '*.png', '*.PNG']
    filepaths = []
    for ext in extensions:
        filepaths.extend(list(image_dir.glob(f'**/{ext}')))

    # Extract labels using pathlib (more robust than os.path.split)
    labels = [x.parent.name for x in filepaths]

    filepaths = pd.Series(filepaths, name='Filepath').astype(str)
    labels = pd.Series(labels, name='Label')

    df = pd.concat([filepaths, labels], axis=1)

    # Identify unique classes and their count
    unique_classes = df['Label'].unique()
    num_classes = len(unique_classes)

    return df, num_classes, unique_classes

dataset = "/kaggle/input/animals10/raw-img"
image_df, n_classes, class_names = convert_path_to_df(dataset)

print(f"Total Images: {len(image_df)}")
print(f"Total Classes Detected: {n_classes}")
print(f"Class List: {sorted(class_names)}")

# Tentukan direktori tujuan
destination_dir = Path('/kaggle/working/animal-10')

# Buat folder utama jika belum ada
if not destination_dir.exists():
    destination_dir.mkdir(parents=True, exist_ok=True)
    print(f"Directory created: {destination_dir}")

print("Copying files... please wait.")

# Loop melalui dataframe untuk menyalin file
# Kita menggunakan path asli dan menyusun path baru berdasarkan Label
for index, row in image_df.iterrows():
    src_path = Path(row['Filepath'])
    label = row['Label']

    # Buat sub-folder untuk setiap kelas di direktori tujuan
    class_dest_dir = destination_dir / label
    class_dest_dir.mkdir(exist_ok=True)

    # Tentukan path file tujuan
    dest_path = class_dest_dir / src_path.name

    # Salin file
    shutil.copy(src_path, dest_path)

print(f"Done! Dataset copied to: {destination_dir}")

# 1. Load file translate.py secara dinamis
spec = importlib.util.spec_from_file_location("translate_module", "/kaggle/input/animals10/translate.py")
translate_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(translate_module)

# 2. Ambil kamus 'translate' dari dalam modul tersebut
# Kita gunakan .get() untuk menghindari error jika nama variabelnya sedikit berbeda
translate = getattr(translate_module, 'translate')

# 3. Eksekusi Rename Folder
working_dir = Path('/kaggle/working/animal-10')

print(f"Menggunakan kamus dari: {spec.origin}")

for folder in working_dir.iterdir():
    if folder.is_dir() and folder.name in translate:
        old_name = folder.name
        new_name = translate[old_name]

        # Eksekusi rename
        folder.rename(working_dir / new_name)
        print(f"Succesfully translated: {old_name} ---> {new_name}")

print("\nCek hasil akhir:")
print(os.listdir(working_dir))

def print_images_resolution(directory, limit=10):
    total_images = 0

    # Iterasi setiap folder kelas
    for subdir in sorted(os.listdir(directory)):
        subdir_path = os.path.join(directory, subdir)
        if not os.path.isdir(subdir_path):
            continue

        image_files = os.listdir(subdir_path)
        num_images = len(image_files)
        print(f"📁 {subdir}: {num_images} images")
        total_images += num_images

        # Gunakan set untuk mencari ukuran unik, tapi kita batasi prosesnya
        unique_sizes = set()

        # islice akan berhenti membaca file setelah mencapai batas 'limit'
        # Ini jauh lebih cepat daripada membaca ribuan gambar
        for img_file in islice(image_files, limit):
            img_path = os.path.join(subdir_path, img_file)
            try:
                with Image.open(img_path) as img:
                    unique_sizes.add(img.size)
            except:
                continue # Lewati jika ada file yang bukan gambar atau korup

        # Cetak sampel resolusi yang ditemukan
        for size in unique_sizes:
            print(f"   - Sample Resolution: {size}")

        print("-" * 30)

    print(f"\n✅ Total Images in Dataset: {total_images}")

# Panggil fungsi dengan limit 10
print_images_resolution('/kaggle/working/animal-10', limit=10)

def visualize_distribution(directory):
    # 1. Ambil data jumlah file per folder
    data = []
    for subdir in os.listdir(directory):
        subdir_path = os.path.join(directory, subdir)
        if os.path.isdir(subdir_path):
            count = len(os.listdir(subdir_path))
            data.append({'Label': subdir, 'Count': count})

    # 2. Masukkan ke DataFrame dan urutkan
    df_dist = pd.DataFrame(data).sort_values(by='Count', ascending=False)

    # 3. Setup Visualisasi
    plt.figure(figsize=(12, 7))
    sns.set_style("whitegrid")

    # Buat Bar Chart
    plot = sns.barplot(x='Label', y='Count', data=df_dist, palette='viridis')

    # Tambahkan angka di atas setiap bar
    for p in plot.patches:
        plot.annotate(format(p.get_height(), '.0f'),
                       (p.get_x() + p.get_width() / 2., p.get_height()),
                       ha = 'center', va = 'center',
                       xytext = (0, 9),
                       textcoords = 'offset points',
                       fontsize=10, fontweight='bold')

    # Label dan Judul
    plt.title('Distribusi Jumlah Gambar per Kelas (Animal-10)', fontsize=16, pad=20)
    plt.xlabel('Nama Hewan', fontsize=12)
    plt.ylabel('Jumlah Gambar', fontsize=12)
    plt.xticks(rotation=45)
    plt.ylim(0, df_dist['Count'].max() + 500) # Beri ruang untuk label angka

    plt.tight_layout()
    plt.show()

# Panggil fungsi
visualize_distribution('/kaggle/working/animal-10')

"""# <font color='yellow'> **Data Splitting**</font>"""

# Tentukan path sumber dan tujuan
input_folder = '/kaggle/working/animal-10'
output_folder = '/kaggle/working/final_dataset' # Folder baru untuk hasil split

# Lakukan split: 80% Train, 10% Val, 10% Test
# seed=1337 memastikan hasil split yang sama jika kode dijalankan ulang
splitfolders.ratio(input_folder, output=output_folder,
                   seed=1337, ratio=(.8, .1, .1),
                   group_prefix=None, move=False)

print("Splitting selesai!")

def check_split(base_path):
    for split in ['train', 'val', 'test']:
        print(f"--- Subset: {split.upper()} ---")
        path = os.path.join(base_path, split)
        for label in sorted(os.listdir(path)):
            num_images = len(os.listdir(os.path.join(path, label)))
            print(f"{label}: {num_images} images")
        print("\n")

check_split('/kaggle/working/final_dataset')

# 1. Setup Konfigurasi
BATCH_SIZE = 64
IMAGE_SIZE = (224, 224) # Sesuaikan dengan rata-rata resolusi dataset Anda
BASE_PATH = '/kaggle/working/final_dataset'

# 2. Augmentasi On-The-Fly dengan ImageDataGenerator
# Untuk Train: Kita tambahkan augmentasi
train_datagen = ImageDataGenerator(
    rescale=1./255,           # Normalisasi pixel ke [0, 1]
    rotation_range=20,        # Rotasi acak
    width_shift_range=0.2,    # Pergeseran horizontal
    height_shift_range=0.2,   # Pergeseran vertikal
    shear_range=0.2,          # Pemangkasan sudut
    zoom_range=0.2,           # Zooming
    horizontal_flip=True,     # Membalik gambar secara horizontal
    fill_mode='nearest'
)

# Untuk Val & Test: Cukup rescale saja (jangan di-augmentasi agar evaluasi fair)
val_test_datagen = ImageDataGenerator(rescale=1./255)

# 3. Load Data dari Direktori
train_generator = train_datagen.flow_from_directory(
    f"{BASE_PATH}/train",
    target_size=IMAGE_SIZE, # Menjaga konsistensi input model
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    color_mode='rgb',
    shuffle=True,
    seed=1337
)

val_generator = val_test_datagen.flow_from_directory(
    f"{BASE_PATH}/val",
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    color_mode='rgb',
    shuffle=False
)

test_generator = val_test_datagen.flow_from_directory(
    f"{BASE_PATH}/test",
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    color_mode='rgb',
    shuffle=False # Penting untuk evaluasi akhir
)

"""# <font color='yellow'> **Modeling**</font>"""

# 1. Load MobileNetV2 sebagai Feature Extractor
base_model = tf.keras.applications.MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3),
    pooling=None
)
base_model.trainable = False # Mengunci bobot pre-trained

# 2. Membangun Model Sequential dengan Conv2D & Pooling tambahan
model = models.Sequential([
    base_model,

    # Tambahan Conv2D dan Pooling sesuai permintaan
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.GlobalAveragePooling2D(), # Mengubah tensor 3D menjadi 1D

    # Dense Layers
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.4),
    layers.Dense(10, activation='softmax') # 10 kelas hewan
])

# 3. Optimizer AdamW dengan Learning Rate & Weight Decay 1e-4
optimizer = AdamW(learning_rate=1e-4, weight_decay=1e-4)

model.compile(
    optimizer=optimizer,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# 1. Callback Tunggal untuk Live Log, Rename Metrik, & Threshold
class MyAnimalCallback(tf.keras.callbacks.Callback):
    def __init__(self, val_gen, threshold=0.96):
        super().__init__()
        self.val_gen = val_gen
        self.threshold = threshold

    def on_epoch_begin(self, epoch, logs=None):
        # Ambil Learning Rate saat ini
        lr = self.model.optimizer.learning_rate
        self.curr_lr = lr.numpy() if hasattr(lr, 'numpy') else tf.keras.backend.get_value(lr)

    def on_train_batch_end(self, batch, logs=None):
        # Ambil sampel kecil untuk Live Validation
        val_imgs, val_lbls = next(self.val_gen)
        val_m = self.model.test_on_batch(val_imgs, val_lbls, return_dict=True)

        # Rename dan Masukkan ke Bar Progres
        logs['train_acc'] = logs.pop('accuracy', 0)
        logs['train_loss'] = logs.pop('loss', 0)
        logs['val_acc'] = val_m['accuracy']
        logs['val_loss'] = val_m['loss']
        logs['lr'] = self.curr_lr

    def on_epoch_end(self, epoch, logs=None):
        # Ambil hasil akhir (evaluasi total oleh Keras)
        ta = logs.get('train_acc', logs.get('accuracy'))
        tl = logs.get('train_loss', logs.get('loss'))
        va = logs.get('val_accuracy')
        vl = logs.get('val_loss')

        print(f"\n" + "="*55)
        print(f"✨ EPOCH {epoch+1} SELESAI")
        print(f"📈 Train: Acc {ta:.4f} | Loss {tl:.4f}")
        print(f"🧪 Valid: Acc {va:.4f} | Loss {vl:.4f}")
        print(f"💡 LR: {self.curr_lr:.2e}")
        print("="*55 + "\n")

        if ta >= self.threshold and va >= self.threshold:
            print(f"🚀 Reached {self.threshold*100}% - STOPPING TRAINING!")
            self.model.stop_training = True

# 2. Scheduler & Eksekusi
def cosine_decay(epoch, lr):
    return 1e-4 * 0.5 * (1 + np.cos(np.pi * epoch / 30))

# Masukkan ke list
callbacks_list = [
    MyAnimalCallback(val_gen=val_generator, threshold=0.96),
    tf.keras.callbacks.LearningRateScheduler(cosine_decay),
    tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint('best_model.keras', monitor='val_accuracy', save_best_only=True)
]

# Bungkam TensorFlow dan XLA
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['XLA_FLAGS'] = '--xla_gpu_strict_colocation=true' # Terkadang membantu stabilitas XLA
os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices=false' # Jika tidak pakai XLA device khusus

# Bungkam log Python standar
logging.getLogger('tensorflow').setLevel(logging.ERROR)

# 3. Jalankan Training
history = model.fit(
    train_generator,
    epochs=30,
    validation_data=val_generator,
    verbose=1,
    callbacks=callbacks_list
)

"""# <font color='yellow'> **Evaluasi dan Visualisasi**</font>"""

# Plot akurasi
plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'], label='Train Accuracy', color='blue', linestyle='solid', marker='o')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='red', linestyle='dashed', marker='s')

# Tambahkan title dan label
plt.title("Perkembangan Akurasi Model", fontsize=14)
plt.xlabel("Epoch", fontsize=12)
plt.ylabel("Accuracy", fontsize=12)

# Tambahkan grid untuk memperjelas pola
plt.grid(True, linestyle="--", alpha=0.6)

# Tambahkan legenda
plt.legend(loc='lower right')

# Cari akurasi terbaik
best_train_acc = max(history.history['accuracy'])
best_val_acc = max(history.history['val_accuracy'])

# Tambahkan anotasi akurasi terbaik pada grafik
plt.annotate(f"Train Max: {best_train_acc:.2%}",
             xy=(history.history['accuracy'].index(best_train_acc), best_train_acc),
             xytext=(-30, 10), textcoords="offset points",
             arrowprops=dict(arrowstyle="->", color="blue"), color="blue")

plt.annotate(f"Val Max: {best_val_acc:.2%}",
             xy=(history.history['val_accuracy'].index(best_val_acc), best_val_acc),
             xytext=(-30, -20), textcoords="offset points",
             arrowprops=dict(arrowstyle="->", color="red"), color="red")

# Tampilkan plot
plt.show()

# Tampilkan akurasi terbaik
print(f"Akurasi terbaik model: {best_train_acc:.2%} pada training dan {best_val_acc:.2%} pada validation.")

# Plot loss
plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Train Loss', color='blue', linestyle='solid', marker='o')
plt.plot(history.history['val_loss'], label='Validation Loss', color='red', linestyle='dashed', marker='s')

# Tambahkan title dan label
plt.title("Perkembangan Loss Model", fontsize=14)
plt.xlabel("Epoch", fontsize=12)
plt.ylabel("Loss", fontsize=12)

# Tambahkan grid untuk memperjelas pola
plt.grid(True, linestyle="--", alpha=0.6)

# Tambahkan legenda
plt.legend(loc='upper right')

# Cari loss terbaik (terendah)
best_train_loss = min(history.history['loss'])
best_val_loss = min(history.history['val_loss'])

# Tambahkan anotasi loss terendah pada grafik
plt.annotate(f"Train Min: {best_train_loss:.4f}",
             xy=(history.history['loss'].index(best_train_loss), best_train_loss),
             xytext=(-30, 10), textcoords="offset points",
             arrowprops=dict(arrowstyle="->", color="blue"), color="blue")

plt.annotate(f"Val Min: {best_val_loss:.4f}",
             xy=(history.history['val_loss'].index(best_val_loss), best_val_loss),
             xytext=(-30, -20), textcoords="offset points",
             arrowprops=dict(arrowstyle="->", color="red"), color="red")

# Tampilkan plot
plt.show()

# Tampilkan loss terbaik
print(f"Loss terbaik model: {best_train_loss:.4f} pada training dan {best_val_loss:.4f} pada validation.")

"""# <font color='yellow'> **Konversi Model (Menyimpan Model)**</font>"""

# Menyimpan model
save_dir = "exported_model/saved_model"
os.makedirs(save_dir, exist_ok=True)
model.export(save_dir)
print("SavedModel berhasil disimpan.")

# Save model keras
model.save("exported_model/model_training.keras")

"""Konversi ke TensorFlow Lite (TFLite)"""

saved_model_dir = "exported_model/saved_model"
tflite_path = "exported_model/model.tflite"
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
with open("exported_model/model_optimized.tflite", "wb") as f:
    f.write(tflite_model)
print("Model TFLite optimized berhasil dibuat.")

"""Konversi ke TensorFlow.js (TFJS)"""

input_path = "exported_model/saved_model"
output_path = "exported_model/tfjs_model"
cmd = [
    "tensorflowjs_converter",
    "--input_format=tf_saved_model",
    "--output_format=tfjs_graph_model",
    input_path,
    output_path
]
subprocess.run(cmd)
print("Model TFJS berhasil dibuat.")

"""# <font color='yellow'> **Inference atau Testing**</font>"""

# Load savedmodel dengan tf serving
model_path = "exported_model/saved_model"

loaded_model = tf.saved_model.load(model_path)
infer = loaded_model.signatures["serving_default"]

print("Model berhasil dimuat.")

"""## Bentuk Folder Test"""

# Test ke dataset test
y_true = []
y_pred = []

for batch_x, batch_y in tqdm(test_generator):

    # konversi tensor
    input_tensor = tf.convert_to_tensor(batch_x, dtype=tf.float32)

    # inference ala TF Serving
    outputs = infer(input_tensor)

    # ambil output tensor
    preds = list(outputs.values())[0].numpy()

    y_true.extend(np.argmax(batch_y, axis=1))
    y_pred.extend(np.argmax(preds, axis=1))

    # stop jika sudah satu epoch
    if len(y_true) >= test_generator.samples:
        break

acc = accuracy_score(y_true, y_pred)
print(f"Akurasi Test (SavedModel Inference): {acc*100:.2f}%")

print(classification_report(
    y_true,
    y_pred,
    target_names=list(test_generator.class_indices.keys())
))

# 1. Hitung ulang CM (pastikan y_true dan y_pred sudah siap)
cm = confusion_matrix(y_true, y_pred)
class_names = list(test_generator.class_indices.keys())

# 2. Plotting
plt.figure(figsize=(10, 10))
plt.imshow(cm, cmap="Blues", interpolation='nearest') # 'nearest' membantu ketajaman kotak
plt.title("Confusion Matrix - Animal 10", fontsize=16, pad=20)
plt.colorbar(fraction=0.046, pad=0.04) # Ukuran colorbar yang proporsional
plt.grid(False) # Mematikan grid otomatis yang menabrak angka
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names, rotation=45, ha='right')
plt.yticks(tick_marks, class_names)

# Angka di setiap sel dengan logika warna adaptif
thresh = cm.max() / 2.
for i in range(len(class_names)):
    for j in range(len(class_names)):
        plt.text(j, i, format(cm[i, j], 'd'),
                 ha="center", va="center",
                 color="white" if cm[i, j] > thresh else "black",
                 fontsize=11)

plt.ylabel("True Label", fontsize=12, fontweight='bold')
plt.xlabel("Predicted Label", fontsize=12, fontweight='bold')

# Mengunci aspek ratio agar tetap kotak sempurna
plt.gca().set_aspect('equal', adjustable='box')
plt.tight_layout()
plt.show()

"""## Bentuk Upload Gambar"""

IMAGE_SIZE = (224, 224)

def preprocess_image(img_path):
    img = image.load_img(img_path, target_size=IMAGE_SIZE)
    img_array = image.img_to_array(img)

    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    return tf.convert_to_tensor(img_array, dtype=tf.float32)

IMAGE_SIZE = (224, 224)
class_labels = list(test_generator.class_indices.keys())

def predict_uploaded_image(img_path, infer):
    # load gambar
    img = image.load_img(img_path, target_size=IMAGE_SIZE)
    img_array = image.img_to_array(img)
    # normalisasi sama seperti training
    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    input_tensor = tf.convert_to_tensor(img_array, dtype=tf.float32)
    # hitung waktu inference
    start_time = time.time()
    outputs = infer(input_tensor)
    end_time = time.time()
    preds = list(outputs.values())[0].numpy()
    pred_index = np.argmax(preds, axis=1)[0]
    predicted_label = class_labels[pred_index]
    confidence = float(np.max(preds))
    latency = end_time - start_time
    return img, predicted_label, confidence, latency

image_path = "/kaggle/input/animals10/raw-img/cane/OIP--HjjWS524SecIyPDEh8GNgHaJ4.jpeg"
print(f"Gambar yang diunggah: {image_path}")

# prediksi
img, predicted_label, confidence, latency = predict_uploaded_image(
    image_path,
    infer
)

# tampilkan gambar
plt.imshow(img)
plt.axis("off")
plt.title(f"Prediksi: {predicted_label}")
plt.show()

# tampilkan detail
print(f"Prediksi kelas: {predicted_label}")
print(f"Probabilitas: {confidence:.4f}")
print(f"Waktu inference: {latency:.4f} detik")

image_path = "/kaggle/input/animals10/raw-img/farfalla/OIP--YxmjyUUbmVOTOwA5fv3XgHaFL.jpeg"
print(f"Gambar yang diunggah: {image_path}")

# prediksi
img, predicted_label, confidence, latency = predict_uploaded_image(
    image_path,
    infer
)

# tampilkan gambar
plt.imshow(img)
plt.axis("off")
plt.title(f"Prediksi: {predicted_label}")
plt.show()

# tampilkan detail
print(f"Prediksi kelas: {predicted_label}")
print(f"Probabilitas: {confidence:.4f}")
print(f"Waktu inference: {latency:.4f} detik")

image_path = "/kaggle/input/animals10/raw-img/mucca/OIP--c6Kv6abukQvmc3gYdKvLwHaFS.jpeg"
print(f"Gambar yang diunggah: {image_path}")

# prediksi
img, predicted_label, confidence, latency = predict_uploaded_image(
    image_path,
    infer
)

# tampilkan gambar
plt.imshow(img)
plt.axis("off")
plt.title(f"Prediksi: {predicted_label}")
plt.show()

# tampilkan detail
print(f"Prediksi kelas: {predicted_label}")
print(f"Probabilitas: {confidence:.4f}")
print(f"Waktu inference: {latency:.4f} detik")

pip freeze requirements.txt